---
# [en_US] Mouse positions corrected by pixel density
#
# [pt_BR] Posições do mouse corrigidas pela densidade de pixel
#
positions: 
  percentageX: 0.5
  percentageY: 0.5
#
# [en_US] Number of screenshots to be taken
#
# [pt_BR] Número de fotos da tela a serem tiradas
#
numberOfScreenshots: 100
#
# [en_US] Initial time before starting to take screen shots
#
# [pt_BR] Tempo inicial antes de começar a tirar as fotos da tela
#
initialDelay: 1
#
# [en_US] Time between the actions of moving to next page and take screenshot
#
# [pt_BR] Tempo entre as ações de passar pra próxima tela e tirar o print
#
timeBetweenActions: 0.3
#
# [en_US] Position of the screen to take the screenshot
#
# [pt_BR] Posição da tela para tirar a foto da tela
#
screenshotPosition: 
  top: 35
  left: 430
  width: 580
  height: 800